### ISSUE TITLE
月份不能往后拨

### ISSUE THREAD

**Issue by kpioneer123** [landscapeside/DragCalendar#3]
1.月份不能往后拨
2.月份收起动画很死板
3.不能选择年

**Comment by landscapeside** [comment]
1.这是我项目中需求决定，如果需要修改，直接修改[CalendarType](https://github.com/landscapeside/DragCalendar/blob/master/app/src/main/java/com/landscape/dragcalendar/conf/CalendarType.java)
2.这是仿小米日历动画效果，目前还没支持更灵活的动画扩展
3.这也是需求，本来目前小米的日历选择年也是采用在另外对话框选择的方式
